<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKUwFose\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKUwFose/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKUwFose.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKUwFose\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKUwFose\App_KernelDevDebugContainer([
    'container.build_hash' => 'KUwFose',
    'container.build_id' => '3f8f008a',
    'container.build_time' => 1676316853,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKUwFose');
